### ISSUE TITLE
StructuredProperty / MessageField cannot be parsed FromMessage

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/endpoints-proto-datastore#143]
See http://stackoverflow.com/questions/36241087/post-an-ndb-structuredproperty-message-decoded-fields#

Explanation:

[`decode_message`][1] doesn't manage to set `_Message__decoded_fields` on nested message types (as we have here).

Simple repro:

```python
from google.appengine.ext import ndb
from endpoints_proto_datastore.ndb import EndpointsModel
from endpoints_proto_datastore.utils import _EPDProtoJson

class Check(EndpointsModel):
  this = ndb.StringProperty()
  that = ndb.StringProperty()

class CheckMessage(EndpointsModel):
  check = ndb.StructuredProperty(Check)

check_msg_type = CheckMessage.ProtoModel(fields=None)
check_msg_val = _EPDProtoJson().decode_message(
    check_msg_type,
    '{"check": {"this": "test", "that": "test"}}',
)
native_obj = CheckMessage.FromMessage(check_msg_val)
```

and it errors out with

```python
Traceback (most recent call last):
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/request_handler.py", line 226, in handle_interactive_request
    exec(compiled_code, self._command_globals)
  File "<string>", line 17, in <module>
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1233, in FromMessage
    if not isinstance(value, (list, tuple)):
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 139, in FromValue
    return modelclass.FromMessage(value)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1217, in FromMessage
    import logging
AttributeError: 'Check' object has no attribute '_Message__decoded_fields'
```

----

**Previous description**
When using

```python
class Check(EndpointsModel):
    this = ndb.StringProperty()
    that = ndb.StringProperty()

class CheckMessage(EndpointsModel):
    check = ndb.StructuredProperty(Check)

@endpoints.api(name='myapi', version='v1', description='My Little API')
class MyApi(remote.Service):

    @CheckMessage.method(name='check_insert', path='check/insert',
                         http_method='POST')
    def check_insert(self, request):
        print(request)
```

the API errors out. Both

```bash
$ curl --header "Content-Type: application/json" \
>     -X POST -d '{}' \
>     http://localhost:8080/_ah/api/myapi/v1/check/insert
$ curl --header "Content-Type: application/json" \
>     -X POST -d '{"check": {"this": "test", "that": "test"}}' \
>     http://localhost:8080/_ah/api/myapi/v1/check/insert
```

both return

```json
{
 "error": {
  "code": 503,
  "errors": [
   {
    "domain": "global",
    "message": "Internal Server Error",
    "reason": "backendError"
   }
  ],
  "message": "Internal Server Error"
 }
}
```

and the `dev_appserver` returns

```python
ERROR    2016-03-30 16:47:30,031 service.py:191] Encountered unexpected error from ProtoRPC method implementation: AttributeError ('NoneType' object has no attribute 'ToMessage')
Traceback (most recent call last):
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
    response = method(instance, request)
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/endpoints-1.0/endpoints/api_config.py", line 1331, in invoke_remote
    return remote_method(service_instance, request)
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0/protorpc/remote.py", line 414, in invoke_remote_method
    response = method(service_instance, request)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1422, in EntityToRequestMethod
    response = response.ToMessage(fields=response_fields)
AttributeError: 'NoneType' object has no attribute 'ToMessage'
```

in the `{}` case and

```python
ERROR    2016-03-30 16:49:12,690 service.py:191] Encountered unexpected error from ProtoRPC method implementation: AttributeError ('Check' object has no attribute '_Message__decoded_fields')
Traceback (most recent call last):
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
    response = method(instance, request)
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/endpoints-1.0/endpoints/api_config.py", line 1331, in invoke_remote
    return remote_method(service_instance, request)
  File "/Users/FOO/google-cloud-sdk/platform/google_appengine/lib/protorpc-1.0/protorpc/remote.py", line 414, in invoke_remote_method
    response = method(service_instance, request)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1408, in EntityToRequestMethod
    request = cls.FromMessage(request)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1232, in FromMessage
    to_add = FromValue(value_property, value)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 139, in FromValue
    return modelclass.FromMessage(value)
  File "/Users/FOO/endpoints-proto-datastore/examples/iss36241087/endpoints_proto_datastore/ndb/model.py", line 1216, in FromMessage
    if not field.name in message._Message__decoded_fields:
AttributeError: 'Check' object has no attribute '_Message__decoded_fields'
```

in the other case.

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/bf241d611d9aee4f0da6a6b39c31cdd9cbfad74c/endpoints_proto_datastore/utils.py#L431

**Comment by dhermes** [comment]
See also http://stackoverflow.com/questions/35673294/how-to-post-ndb-structuredproperty/36240244#36240244

**Comment by dhermes** [comment]
OK the `{}` error was caused by the fact that the API method doesn't return the desired type. It should instead be

```python
    @CheckMessage.method(name='check_insert', path='check/insert',
                         http_method='POST')
    def check_insert(self, request):
        print(request)
        return request
```
